# FLOPs   GMACs   Params.(M)
#  99.38   49.32   1.689
# Throughput (ins./s): 2.445071321282616 

criterion_args:
  NAME: vMFLoss
  start_epoch: 101
  ignore_index: 255
  loss_type: pce

# data augmentation
dataset:
  common:
    NAME: S3DIS
    data_root: /dataset
    data_raw: sparse
    test_area: 5
    voxel_size: 0.04
    rate: 0
    lads: False
  train:
    split: train
    voxel_max: 24000
    loop: 30  # here, the training has been looped 30 times. therefore, the training epochs do not need much.
    presample: False
  val:
    split: val
    voxel_max: null
    presample: True
  test:
    split: test
    voxel_max: null
    presample: False 
  
model:
  NAME: BaseSeg
  encoder_args:
    NAME: PTSeg
    blocks: [2, 3, 4, 6, 3]
    in_channels: 4
  cls_args:
    NAME: SegHead
    num_classes: 13
    in_channels: 256
    norm_args:
      norm: 'bn'

batch_size: 8